# Generated by Django 5.2.7 on 2025-12-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('farmer', 'Farmer'), ('buyer', 'Buyer')], max_length=10),
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
